[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube

upload_protocol = jlink
debug_tool = jlink

monitor_port = COM9
monitor_speed = 115200

board_build.ldscript = STM32F411CEUX_FLASH.ld
board_build.stm32cube.custom_config_header = yes

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F411xE
    -ICore/Inc
    -IUSB_DEVICE/App
    -IUSB_DEVICE/Target
    -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc
    -IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
